'use strict';
const $=s=>document.querySelector(s);

class AudioHouse{
  constructor(){this.ctx=null;this.master=null;this.enabled=false;this.muted=false;this.volume=.55;this.step=0;this.timer=null}
  async start(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.setVolume(this.volume)} if(this.ctx.state==='suspended')await this.ctx.resume();this.enabled=true;this.music()}
  setVolume(v){this.volume=Number(v);if(this.master)this.master.gain.value=this.muted?0:this.volume*.55}
  mute(m){this.muted=m;this.setVolume(this.volume)}
  tone(f,d=.14,type='sine',g=.08,delay=0){if(!this.enabled)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),ga=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);ga.gain.setValueAtTime(.0001,t);ga.gain.exponentialRampToValueAtTime(g,t+.014);ga.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(ga);ga.connect(this.master);o.start(t);o.stop(t+d+.03)}
  noise(d=.18,g=.06,filter=650){if(!this.enabled)return;const t=this.ctx.currentTime,buf=this.ctx.createBuffer(1,Math.max(1,this.ctx.sampleRate*d),this.ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),ga=this.ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=filter;ga.gain.value=g;src.connect(f);f.connect(ga);ga.connect(this.master);src.start(t)}
  rotate(){this.noise(.16,.05,430);this.tone(135,.16,'sawtooth',.045);this.tone(205,.07,'triangle',.04,.04)}
  foot(){this.tone(690+Math.random()*110,.035,'square',.022)}
  tea(){[523,659,784,1047].forEach((f,i)=>this.tone(f,.32,'triangle',.075,i*.05))}
  chomp(){this.tone(55,.32,'sawtooth',.13);this.noise(.3,.11,230)}
  warn(){[330,255,210].forEach((f,i)=>this.tone(f,.15,'sawtooth',.06,i*.065))}
  win(){[392,494,587,784,988].forEach((f,i)=>this.tone(f,.45,'triangle',.09,i*.1))}
  lose(){[220,185,147,110].forEach((f,i)=>this.tone(f,.5,'sawtooth',.08,i*.12))}
  music(){if(this.timer)clearInterval(this.timer);const seq=[262,330,392,330,294,349,440,349];this.timer=setInterval(()=>{if(!this.enabled||this.muted)return;const f=seq[this.step++%seq.length];this.tone(f,.16,'triangle',.02);this.tone(f/2,.35,'sine',.014,.02)},460)}
}

class Game{
  constructor(){this.canvas=$('#game');this.ctx=this.canvas.getContext('2d');this.audio=new AudioHouse();this.running=false;this.ended=false;this.last=0;this.totalGuests=16;this.toWin=10;this.bind();this.reset()}
  bind(){window.addEventListener('resize',()=>this.resize());this.canvas.addEventListener('click',e=>this.click(e));$('#restartBtn').onclick=()=>{$('#endModal').classList.add('hidden');this.reset(true)};$('#againBtn').onclick=()=>{$('#endModal').classList.add('hidden');this.reset(true)};$('#volume').oninput=e=>this.audio.setVolume(e.target.value);$('#muteBtn').onclick=()=>{this.audio.mute(!this.audio.muted);$('#muteBtn').textContent=this.audio.muted?'🔇':'🔊'};window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m')$('#muteBtn').click();if(e.key.toLowerCase()==='r'){$('#endModal').classList.add('hidden');this.reset(true)}})}
  async play(){await this.audio.start();$('#intro').classList.remove('active');$('#gameScreen').classList.add('active');this.resize();if(!this.running){this.running=true;this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}}
  resize(){const dpr=Math.min(2,window.devicePixelRatio||1),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(820,r.width*dpr);this.canvas.height=Math.max(620,r.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);this.w=this.canvas.width/dpr;this.h=this.canvas.height/dpr;this.computeBoard()}
  computeBoard(){const maxW=Math.min(this.w-58,this.h*1.06);this.cell=Math.floor(Math.min(maxW/4,(this.h-90)/4));this.boardW=this.cell*4;this.boardH=this.cell*4;this.left=(this.w-this.boardW)/2;this.top=(this.h-this.boardH)/2+22}
  reset(keep=false){this.suspicion=0;this.served=0;this.correct=0;this.spawned=0;this.spawnTimer=.8;this.guests=[];this.particles=[];this.floaters=[];this.ended=false;this.time=0;this.shake=0;
    const defs=[
      ['Library','#59466f','corner',1],['Gallery','#704963','straight',0],['Tea Hall','#6d8d62','corner',1],['Tea Exit','#6f9667','straight',1],
      ['Front Hall','#86535c','straight',1],['Parlor','#8e5b77','corner',2],['Blue Room','#496f82','straight',1],['Sitting Room','#6b607f','corner',3],
      ['Mud Room','#6a4b3c','corner',0],['Dining Room','#8a6144','tee',0],['Nursery','#467486','corner',1],['Back Stairs','#6d4f7e','straight',0],
      ['Conservatory','#3f7654','corner',3],['Cellar','#624038','straight',1],['Mouth Hall','#5b1b2a','corner',0],['Mouth Exit','#642033','straight',1]
    ];
    this.rooms=defs.map((d,i)=>({id:i,name:d[0],color:d[1],shape:d[2],rot:d[3],x:i%4,y:Math.floor(i/4),pulse:0,badPulse:0,spin:0,seed:Math.random()*99}));
    this.names=['Ada','Baron','Mina','Lady Teeth','Button','Cousin Hex','Vicar Plum','Snarl','Poppy','Sir Sneer','Aunt Lacey','Doctor Bite','Basil','Duchess Gnash','Nora','Captain Rude'];
    this.types=['kind','bad','kind','bad','kind','bad','kind','bad','kind','bad','kind','bad','kind','bad','kind','bad'];
    this.updateUI(); if(keep){this.audio.rotate(); if(!this.running){this.running=true;this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}}
  }
  baseDoors(shape){if(shape==='straight')return [1,0,1,0];if(shape==='corner')return [1,1,0,0];return [1,1,1,0]}
  doors(r){const b=this.baseDoors(r.shape),out=[0,0,0,0];for(let i=0;i<4;i++)out[(i+r.rot)%4]=b[i];return out}
  roomAt(px,py){const x=Math.floor((px-this.left)/this.cell),y=Math.floor((py-this.top)/this.cell);if(x<0||y<0||x>3||y>3)return null;return this.rooms.find(r=>r.x===x&&r.y===y)}
  click(e){if(this.ended)return;const rect=this.canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*this.w/rect.width,y=(e.clientY-rect.top)*this.h/rect.height,r=this.roomAt(x,y);if(!r)return;r.rot=(r.rot+1)%4;r.pulse=1;r.spin=1;this.shake=Math.max(this.shake,.05);this.audio.rotate();this.float(r,'rotate','#ffe08a');this.roomSpark(r,'#ffd783',10)}
  roomByXY(x,y){return this.rooms.find(r=>r.x===x&&r.y===y)}
  neighbors(room){const dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]],d=this.doors(room),arr=[];for(const [dx,dy,di,odi] of dirs){if(!d[di])continue;const n=this.roomByXY(room.x+dx,room.y+dy);if(n&&this.doors(n)[odi])arr.push({kind:'room',room:n,dir:di})}return arr}
  exitFor(room){const d=this.doors(room);if(room.x===3&&room.y===0)return 'tea';if(room.x===3&&room.y===3)return 'mouth';return null}
  spawn(){if(this.spawned>=this.totalGuests||this.guests.length>=5)return;const id=this.spawned++,type=this.types[id],start=Math.random()<.5?4:8;this.guests.push({id,name:this.names[id],type,room:start,prev:null,t:1.2+Math.random()*.5,move:0,from:start,to:start,stuck:0,age:0,warn:13+Math.random()*5});this.float(this.rooms[start],type==='kind'?'☕ tea guest':'🦷 basement guest',type==='kind'?'#9dffad':'#ff7a87');this.updateUI()}
  targetRoom(g){return this.rooms[g.type==='kind'?3:15]}
  man(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
  decide(g){const here=this.rooms[g.room],exit=this.exitFor(here);if(exit){this.resolve(g,exit);return}
    const opts=this.neighbors(here);if(!opts.length){this.trap(g,here);return}
    const target=this.targetRoom(g);opts.sort((A,B)=>{let da=this.man(A.room,target),db=this.man(B.room,target);if(A.room.id===g.prev)da+=1.4;if(B.room.id===g.prev)db+=1.4;return da-db});
    const next=opts[0].room;g.prev=g.room;g.from=g.room;g.to=next.id;g.room=next.id;g.move=.42;g.t=1.05+Math.random()*.25;g.stuck=0;this.audio.foot()
  }
  trap(g,room){g.stuck++;room.badPulse=1;this.shake=Math.max(this.shake,.12);this.addSuspicion(g.stuck>1?3:1.5,'guest stuck');this.float(room,'stuck!','#ff9cab');this.audio.warn();g.t=1.2}
  resolve(g,exit){const ok=(g.type==='kind'&&exit==='tea')||(g.type==='bad'&&exit==='mouth'),room=this.rooms[g.room];this.guests=this.guests.filter(x=>x!==g);this.served++;if(ok){this.correct++;this.shake=Math.max(this.shake,.08);this.float(room,exit==='tea'?'tea served!':'CHOMP!','#fff0a0');this.burst(room,exit==='tea'?'#fff0a0':'#ff6478');exit==='tea'?this.audio.tea():this.audio.chomp()}else{this.shake=Math.max(this.shake,.22);this.addSuspicion(16,'wrong exit');this.float(room,'wrong exit!','#ff9cab');this.burst(room,'#ff405d');this.audio.warn()}this.updateUI();if(this.correct>=this.toWin)this.end(true);else if(this.spawned>=this.totalGuests&&this.guests.length===0)this.end(false)}
  addSuspicion(n,msg){if(this.ended)return;this.suspicion=Math.min(100,this.suspicion+n);this.floatAt(this.left+this.boardW/2,this.top-18,`+${Math.round(n)} suspicion: ${msg}`,'#ff9cab');this.updateUI();if(this.suspicion>=100)this.end(false)}
  updateUI(){$('#suspicionFill').style.width=this.suspicion+'%';$('#suspicionText').textContent=Math.round(this.suspicion)+'%';$('#scoreText').textContent=`${this.correct}/${this.toWin}`;const waiting=[];for(let i=this.spawned;i<Math.min(this.spawned+8,this.totalGuests);i++)waiting.push({name:this.names[i],type:this.types[i]});$('#guestList').innerHTML=`<div class="queueItem activeQ"><span class="queueIcon">🏠</span><div><b>Inside now</b><small>${this.guests.length} guests moving</small></div><span>${this.correct}/${this.toWin}</span></div>`+waiting.map(g=>`<div class="queueItem"><span class="dot ${g.type}"></span><div><b>${g.name}</b><small>${g.type==='kind'?'wants Tea Exit':'needs Mouth Exit'}</small></div><span class="queueIcon">${g.type==='kind'?'☕':'🦷'}</span></div>`).join('')}
  end(win){if(this.ended)return;this.ended=true;this.running=false;this.shake=.35;$('#endModal').classList.remove('hidden');$('#endTitle').textContent=win?'A Perfectly Polite Dinner':'Suspicion Boils Over';$('#endText').textContent=win?`You routed ${this.correct} guests correctly while several wandered at once. Suspicion ended at ${Math.round(this.suspicion)}%.`:`The dinner party noticed the impossible architecture. Correctly routed: ${this.correct}/${this.toWin}.`;win?this.audio.win():this.audio.lose()}
  float(room,text,color){this.floatAt(this.left+(room.x+.5)*this.cell,this.top+room.y*this.cell+24,text,color)}
  floatAt(x,y,text,color){this.floaters.push({x,y,text,color,life:1.05,vy:-28})}
  burst(room,color){const cx=this.left+(room.x+.5)*this.cell,cy=this.top+(room.y+.5)*this.cell;for(let i=0;i<24;i++)this.particles.push({x:cx,y:cy,vx:(Math.random()*2-1)*120,vy:(Math.random()*2-1)*95,life:.55+Math.random()*.45,color,size:3+Math.random()*4})}
  roomSpark(room,color,count=8){const cx=this.left+(room.x+.5)*this.cell,cy=this.top+(room.y+.5)*this.cell;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,sp=40+Math.random()*90;this.particles.push({x:cx+Math.cos(a)*this.cell*.18,y:cy+Math.sin(a)*this.cell*.18,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.35+Math.random()*.35,color,size:2+Math.random()*3})}}
  loop(t){if(!this.running)return;const dt=Math.min(.05,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.draw();requestAnimationFrame(tt=>this.loop(tt))}
  update(dt){this.time+=dt;this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawn();this.spawnTimer=2.65-Math.min(.45,this.spawned*.025)}for(const g of [...this.guests]){g.age+=dt;if(g.age>g.warn){g.age=0;g.warn=13+Math.random()*5;this.addSuspicion(1.5,'guest impatient');this.float(this.rooms[g.room],'hurry!','#ffcf8a')}if(g.move>0)g.move=Math.max(0,g.move-dt);else{g.t-=dt;if(g.t<=0)this.decide(g)}}for(const r of this.rooms){r.pulse=Math.max(0,r.pulse-dt*2.4);r.badPulse=Math.max(0,r.badPulse-dt*2.5);r.spin=Math.max(0,(r.spin||0)-dt*3.4)}this.shake=Math.max(0,this.shake-dt*2.8);for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=95*dt}this.particles=this.particles.filter(p=>p.life>0);for(const f of this.floaters){f.life-=dt;f.y+=f.vy*dt}this.floaters=this.floaters.filter(f=>f.life>0)}
  draw(){const c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);this.drawBackground(c,w,h);c.save();if(this.shake>0){const a=this.shake*7;c.translate((Math.random()*2-1)*a,(Math.random()*2-1)*a)}this.drawHouse(c);this.drawGuests(c);this.drawParticles(c);this.drawFloaters(c);c.restore();this.drawVignette(c,w,h)}

  drawBackground(c,w,h){const bg=c.createRadialGradient(w*.48,h*.18,20,w/2,h*.55,h*.86);bg.addColorStop(0,'#533044');bg.addColorStop(.42,'#24121c');bg.addColorStop(1,'#070306');c.fillStyle=bg;c.fillRect(0,0,w,h);c.globalAlpha=.28;c.fillStyle='#fff1ba';c.beginPath();c.arc(w*.78,h*.13,38+Math.sin(this.time)*2,0,7);c.fill();c.globalAlpha=1;for(let i=0;i<34;i++){const x=(i*137)%w,y=70+((i*83)%Math.max(100,h-140));c.fillStyle=`rgba(255,225,150,${.08+((i%5)/30)})`;c.fillRect(x,y,2,2)}c.fillStyle='rgba(0,0,0,.24)';for(let i=0;i<7;i++){const x=i*w/6;c.beginPath();c.ellipse(x,h+12,120,70,0,Math.PI,0,true);c.fill()}}
  drawVignette(c,w,h){const v=c.createRadialGradient(w/2,h/2,Math.min(w,h)*.25,w/2,h/2,Math.max(w,h)*.68);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.55)');c.fillStyle=v;c.fillRect(0,0,w,h)}
  drawHouse(c){const t=this.time;c.save();c.shadowColor='rgba(0,0,0,.75)';c.shadowBlur=34;c.fillStyle='#0e0509';c.fillRect(this.left-22,this.top-22,this.boardW+44,this.boardH+50);c.restore();const roof=c.createLinearGradient(0,this.top-92,0,this.top);roof.addColorStop(0,'#4a2031');roof.addColorStop(1,'#1d0c13');c.fillStyle=roof;c.beginPath();c.moveTo(this.left-42,this.top-26);c.lineTo(this.left+this.boardW/2,this.top-92);c.lineTo(this.left+this.boardW+42,this.top-26);c.closePath();c.fill();c.fillStyle='#16080e';c.fillRect(this.left+this.boardW*.17,this.top-92,28,54);c.fillStyle='rgba(80,80,90,.25)';for(let i=0;i<4;i++){c.beginPath();c.ellipse(this.left+this.boardW*.17+14+Math.sin(t+i)*7,this.top-105-i*13,15+i*5,7+i*2,0,0,7);c.fill()}c.fillStyle='#13070d';c.fillRect(this.left-16,this.top-16,this.boardW+32,this.boardH+32);for(const r of this.rooms)this.drawRoom(c,r);this.drawExternal(c);this.drawSharedDoorGlows(c);c.strokeStyle='rgba(229,184,92,.7)';c.lineWidth=5;c.shadowColor='rgba(255,210,100,.35)';c.shadowBlur=10;c.strokeRect(this.left-2,this.top-2,this.boardW+4,this.boardH+4);c.shadowBlur=0;for(let i=0;i<5;i++){const x=this.left+18+i*(this.boardW-36)/4;c.fillStyle=`rgba(255,185,80,${.45+.25*Math.sin(t*5+i)})`;c.beginPath();c.ellipse(x,this.top+this.boardH+24,4,9,0,0,7);c.fill();c.fillStyle='rgba(255,230,120,.22)';c.beginPath();c.arc(x,this.top+this.boardH+24,18,0,7);c.fill()}}

  drawRoom(c,r){const x=this.left+r.x*this.cell,y=this.top+r.y*this.cell,s=this.cell;c.save();c.translate(x,y);const grad=c.createLinearGradient(0,0,s,s);grad.addColorStop(0,r.color);grad.addColorStop(1,'#1b0d13');c.fillStyle=grad;c.fillRect(5,5,s-10,s-10);c.fillStyle='rgba(255,255,255,.035)';for(let i=10;i<s;i+=14){c.fillRect(i,9,3,s-18)}c.strokeStyle='rgba(255,255,255,.045)';for(let i=12;i<s;i+=15){c.beginPath();c.moveTo(i,8);c.lineTo(i-20,s-8);c.stroke()}this.drawRoomDecor(c,r,s);if(r.pulse){c.fillStyle=`rgba(255,222,138,${r.pulse*.23})`;c.fillRect(5,5,s-10,s-10);c.strokeStyle=`rgba(255,235,160,${r.pulse})`;c.lineWidth=3+5*r.pulse;c.strokeRect(10,10,s-20,s-20)}if(r.badPulse){c.fillStyle=`rgba(255,30,70,${r.badPulse*.22})`;c.fillRect(5,5,s-10,s-10);c.strokeStyle=`rgba(255,80,110,${r.badPulse})`;c.lineWidth=5;c.strokeRect(9,9,s-18,s-18)}c.fillStyle='rgba(20,8,12,.38)';c.fillRect(10,7,s-20,20);c.fillStyle='#ffe0a0';c.font=`bold ${Math.max(12,s*.066)}px Georgia`;c.textAlign='center';c.shadowColor='rgba(0,0,0,.75)';c.shadowBlur=4;c.fillText(r.name,s/2,22);c.shadowBlur=0;this.drawHall(c,r,s);c.restore()}

  drawRoomDecor(c,r,s){c.save();c.globalAlpha=.36;c.fillStyle='rgba(255,225,155,.55)';c.strokeStyle='rgba(25,8,13,.65)';c.lineWidth=3;const name=r.name;if(name.includes('Library')){for(let i=0;i<5;i++)c.fillRect(18+i*9,s*.58,6,35)}else if(name.includes('Gallery')){c.strokeRect(s*.35,s*.46,42,32);c.fillText('👁',s*.46,s*.62)}else if(name.includes('Tea')){c.font='26px serif';c.fillText('☕',s*.58,s*.62);c.fillText('✦',s*.28,s*.42)}else if(name.includes('Front')){c.beginPath();c.arc(s*.22,s*.32,18,0,7);c.stroke();c.fillText('🕯',s*.76,s*.68)}else if(name.includes('Parlor')){c.fillRect(s*.32,s*.62,58,14);c.fillStyle='rgba(20,8,12,.7)';for(let i=0;i<6;i++)c.fillRect(s*.34+i*8,s*.62,4,14)}else if(name.includes('Blue')||name.includes('Sitting')){c.strokeRect(s*.42,s*.48,38,38);c.fillText('👁',s*.48,s*.66)}else if(name.includes('Mud')||name.includes('Cellar')){c.fillText('🕸',s*.25,s*.34);c.fillText('▥',s*.7,s*.7)}else if(name.includes('Dining')){c.fillText('🍽',s*.55,s*.66)}else if(name.includes('Nursery')){c.fillText('🧸',s*.58,s*.64)}else if(name.includes('Back')){c.fillText('↯',s*.55,s*.6)}else if(name.includes('Conservatory')){c.fillText('♣ ♣',s*.38,s*.64)}else if(name.includes('Mouth')){c.fillText('✧',s*.28,s*.38);c.fillText('🦷',s*.68,s*.66)}c.restore()}
  drawHall(c,r,s){const d=this.doors(r),cx=s/2,cy=s/2+8,spin=(r.spin||0);c.save();c.translate(cx,cy);if(spin>0)c.rotate(-spin*Math.PI/2);c.translate(-cx,-cy);c.lineCap='round';c.lineJoin='round';c.shadowColor='rgba(255,222,120,.72)';c.shadowBlur=12+8*Math.sin(this.time*4+r.seed);c.strokeStyle='rgba(35,15,18,.62)';c.lineWidth=s*.30;for(let i=0;i<4;i++)if(d[i]){c.beginPath();c.moveTo(cx,cy);if(i===0)c.lineTo(cx,6);if(i===1)c.lineTo(s-6,cy);if(i===2)c.lineTo(cx,s-6);if(i===3)c.lineTo(6,cy);c.stroke()}c.strokeStyle='rgba(255,225,142,.96)';c.lineWidth=s*.19;for(let i=0;i<4;i++)if(d[i]){c.beginPath();c.moveTo(cx,cy);if(i===0)c.lineTo(cx,9);if(i===1)c.lineTo(s-9,cy);if(i===2)c.lineTo(cx,s-9);if(i===3)c.lineTo(9,cy);c.stroke()}c.strokeStyle='rgba(255,255,220,.45)';c.lineWidth=s*.055;for(let i=0;i<4;i++)if(d[i]){c.beginPath();c.moveTo(cx,cy);if(i===0)c.lineTo(cx,12);if(i===1)c.lineTo(s-12,cy);if(i===2)c.lineTo(cx,s-12);if(i===3)c.lineTo(12,cy);c.stroke()}c.shadowBlur=10;c.fillStyle='rgba(255,250,205,.98)';c.beginPath();c.arc(cx,cy,s*.08+Math.sin(this.time*5+r.seed)*1.2,0,7);c.fill();c.shadowBlur=0;c.lineWidth=8;c.strokeStyle='#ffd783';if(d[0]){c.beginPath();c.moveTo(s*.38,5);c.lineTo(s*.62,5);c.stroke()}if(d[1]){c.beginPath();c.moveTo(s-5,s*.38);c.lineTo(s-5,s*.62);c.stroke()}if(d[2]){c.beginPath();c.moveTo(s*.38,s-5);c.lineTo(s*.62,s-5);c.stroke()}if(d[3]){c.beginPath();c.moveTo(5,s*.38);c.lineTo(5,s*.62);c.stroke()}c.restore();if(spin>0){c.save();c.strokeStyle=`rgba(255,238,160,${spin})`;c.lineWidth=3;c.setLineDash([8,8]);c.beginPath();c.arc(cx,cy,s*.34*(1-spin*.2),0,Math.PI*2);c.stroke();c.restore()}}

  drawSharedDoorGlows(c){for(const r of this.rooms){const d=this.doors(r);if(d[1]){const n=this.roomByXY(r.x+1,r.y);if(n&&this.doors(n)[3])this.edgeGlow(c,r.x+1,r.y,'v')}if(d[2]){const n=this.roomByXY(r.x,r.y+1);if(n&&this.doors(n)[0])this.edgeGlow(c,r.x,r.y+1,'h')}}}
  edgeGlow(c,gx,gy,type){const x=this.left+gx*this.cell,y=this.top+gy*this.cell;c.save();c.shadowColor='#fff5a8';c.shadowBlur=14;c.strokeStyle='rgba(255,250,170,.8)';c.lineWidth=4;c.lineCap='round';c.beginPath();if(type==='v'){c.moveTo(x,y+this.cell*.38);c.lineTo(x,y+this.cell*.62)}else{c.moveTo(x+this.cell*.38,y);c.lineTo(x+this.cell*.62,y)}c.stroke();c.restore()}
  drawExternal(c){const s=this.cell,t=this.time;c.save();c.font='bold 17px Georgia';c.textAlign='center';[['Front Door',-.08,1.5,'#ffd783'],['Tea ☕',4.08,.5,'#a8ffad'],['Mouth 🦷',4.08,3.5,'#ff7387']].forEach(([txt,gx,gy,col])=>{const x=this.left+gx*s,y=this.top+gy*s;c.fillStyle=col;c.strokeStyle='rgba(0,0,0,.65)';c.lineWidth=5;c.shadowColor=col;c.shadowBlur=10;c.strokeText(txt,x,y-20);c.fillText(txt,x,y-20)});c.shadowBlur=0;c.strokeStyle='rgba(255,216,128,.9)';c.lineWidth=8;c.lineCap='round';c.beginPath();c.moveTo(this.left-8,this.top+1.5*s);c.lineTo(this.left+8,this.top+1.5*s);c.moveTo(this.left+this.boardW-8,this.top+.5*s);c.lineTo(this.left+this.boardW+8,this.top+.5*s);c.moveTo(this.left+this.boardW-8,this.top+3.5*s);c.lineTo(this.left+this.boardW+8,this.top+3.5*s);c.stroke();const tx=this.left+this.boardW+28,ty=this.top+.5*s;c.font='34px serif';c.fillStyle='#f8ffe0';c.fillText('☕',tx,ty+10);c.strokeStyle='rgba(230,255,220,.45)';c.lineWidth=2;for(let i=0;i<3;i++){c.beginPath();c.moveTo(tx-14+i*9,ty-8);c.bezierCurveTo(tx-22+i*9,ty-24-5*Math.sin(t+i),tx-5+i*9,ty-32,tx-14+i*9,ty-45);c.stroke()}const mx=this.left+this.boardW+28,my=this.top+3.5*s+6;c.fillStyle='#18030a';c.beginPath();c.ellipse(mx,my,31,23+Math.sin(t*5)*3,0,0,7);c.fill();c.fillStyle='#fff2c8';for(let i=-2;i<=2;i++){c.beginPath();c.moveTo(mx+i*10,my-18);c.lineTo(mx+i*10+4,my-5);c.lineTo(mx+i*10-4,my-5);c.fill()}c.fillStyle='#c72a4d';c.beginPath();c.ellipse(mx,my+7,14,6,0,0,7);c.fill();c.restore()}

  guestPos(g){const s=this.cell;let a=this.rooms[g.room],x=this.left+(a.x+.5)*s,y=this.top+(a.y+.62)*s;if(g.move>0){const from=this.rooms[g.from],to=this.rooms[g.to],k=1-g.move/.42;x=this.left+(from.x+.5+(to.x-from.x)*k)*s;y=this.top+(from.y+.62+(to.y-from.y)*k)*s}return{x,y}}
  drawGuests(c){const counts={};for(const g of this.guests){const p=this.guestPos(g),key=g.room;counts[key]=(counts[key]||0)+1;const off=(counts[key]-1)*12,wob=Math.sin(this.time*9+g.id)*2;c.save();c.translate(p.x+off-8,p.y+wob);c.fillStyle='rgba(0,0,0,.35)';c.beginPath();c.ellipse(0,24,20,7,0,0,7);c.fill();c.fillStyle=g.type==='kind'?'rgba(120,255,150,.18)':'rgba(255,80,105,.18)';c.beginPath();c.arc(0,2,31,0,7);c.fill();c.fillStyle=g.type==='kind'?'#86ef9a':'#ff687d';c.beginPath();c.arc(0,-13,14,0,7);c.fill();c.fillRect(-11,-1,22,29);c.fillStyle=g.type==='kind'?'#dcffdf':'#ffd7de';c.beginPath();c.arc(-5,-15,2,0,7);c.arc(5,-15,2,0,7);c.fill();c.strokeStyle='#1a0810';c.lineWidth=2;c.beginPath();c.moveTo(-5,-8);c.quadraticCurveTo(0,-5,5,-8);c.stroke();c.fillStyle='#1a0810';c.font='bold 12px Georgia';c.textAlign='center';c.fillText(g.name[0],0,9);c.font='22px serif';c.fillStyle='#fff0a0';c.shadowColor='rgba(255,240,120,.85)';c.shadowBlur=8;c.fillText(g.type==='kind'?'☕':'🦷',0,-34);c.shadowBlur=0;const urgency=Math.max(0,g.age/g.warn);c.strokeStyle=urgency>.72?'#ff677b':'rgba(255,240,160,.75)';c.lineWidth=3;c.beginPath();c.arc(0,-13,23,-Math.PI/2,-Math.PI/2+Math.max(0,g.t/1.25)*Math.PI*2);c.stroke();if(urgency>.72){c.fillStyle='#ffcf8a';c.font='bold 15px Georgia';c.fillText('!',18,-25)}c.restore()}}

  drawParticles(c){for(const p of this.particles){c.globalAlpha=Math.max(0,p.life);c.fillStyle=p.color;c.shadowColor=p.color;c.shadowBlur=10;c.beginPath();c.arc(p.x,p.y,(p.size||4)+p.life*3,0,7);c.fill()}c.shadowBlur=0;c.globalAlpha=1}

  drawFloaters(c){for(const f of this.floaters){c.globalAlpha=Math.min(1,f.life);c.font='bold 19px Georgia';c.textAlign='center';c.shadowColor=f.color;c.shadowBlur=12;c.strokeStyle='#12080c';c.lineWidth=5;c.strokeText(f.text,f.x,f.y);c.fillStyle=f.color;c.fillText(f.text,f.x,f.y)}c.shadowBlur=0;c.globalAlpha=1}

}
const game=new Game();$("#playBtn").addEventListener("click",()=>game.play());
